### ISSUE TITLE
Tokenizer Format Question

### ISSUE THREAD

**Issue by rabbidave** [kyegomez/Med-PaLM#5]
The sample code uses random values to demonstrate functionality.

I'm unable to infer which tokenizer or module to use when I'm passing my own image via URL, local path, etc.

Same for defining simultaneous text input 

e.g. describe any abnormalities in this image of the interior of the eye (URL to image of detaching retina)

Can you please either provide an additional example or help me understand what module I should be calling, format I should be using, etc.

**Comment by siavashk** [comment]
This repository is fake and the user is spamming to increase their visibility. They have a history of copying / setting up fake repositories to boost their profile. For example they have copied the Tree of Thoughts repository and will not take their fake repo down. See the relevant discussion in the [original repository](https://github.com/princeton-nlp/tree-of-thought-llm/issues/17) and the [fake repository](https://github.com/kyegomez/tree-of-thoughts/issues/54).

It would be great if you could spread the word so that Github would take some action against them.
![image](https://github.com/kyegomez/Med-PaLM/assets/1020752/6d2b9451-9a9b-4f4d-bab5-b3aef6e8a081)

**Comment by rabbidave** [comment]
Reported; appreciate your diligence and specificity

**Comment by kyegomez** [comment]
@rabbidave Yes, the tokenizer to use should be GPTNeox, with the image embeddings passed in as special tokens.

**Comment by kyegomez** [comment]
@rabbidave And, you are extremely gullible you just obeyed his command without any sort of evidence or backings for his claim.

**Comment by siavashk** [comment]
@kyegomez I provided evidence for your plagiarism, i.e. Tree of Thought (https://github.com/pypi/support/issues/2928). You have stolen from other projects as well, for example Sophia (https://github.com/kyegomez/Sophia/issues/27). @rabbidave is free to make his own conclusions.

You can delete this comment if you want but you have already developed a reputation in machine learning for intellectual theft. If you are indeed 19 years old, you might want to reconsider your path and use your skills to create your own original ideas instead of stealing from others.

**Comment by kyegomez** [comment]
@siavashk How did i plagiarize tree of thoughts? I implemented it faster than the original authors did.

And, I did copy code from Sophia because my code was worse than theirs and I didn't want people to use my bad code.

Pablo Picasso one of the best artists of all time is widely quoted as having said that “good artists borrow, great artists steal.”

Everybody steals.

**Comment by siavashk** [comment]
I do not have anything else to say to you because I am not trying to convince you. I think there is enough information here for people to form their opinion.

**Comment by kyegomez** [comment]
@siavashk im very curious what do you think my intentions are? You know I'm doing this to advance our species right? 

You're trying to discredit someone who works 24/7 to help Humanity, you should be ashamed of yourself.
